project_id = "hulwcntfioqifopyjcvv"

[functions.maxlist-import]
verify_jwt = false

[functions.process-email-queue]
verify_jwt = true

[functions.send-bulk-whatsapp]
verify_jwt = false

[functions.mcp-server]
verify_jwt = false